diff --git a/sound/soc/bcm/Makefile b/sound/soc/bcm/Makefile
index 53ea8229d..94562e6be 100644
--- a/sound/soc/bcm/Makefile
+++ b/sound/soc/bcm/Makefile
@@ -64,3 +64,6 @@ obj-$(CONFIG_SND_BCM2708_SOC_ALLO_PIANO_DAC_PLUS) += snd-soc-allo-piano-dac-plus
 obj-$(CONFIG_SND_BCM2708_SOC_ALLO_DIGIONE) += snd-soc-allo-digione.o
 obj-$(CONFIG_SND_PISOUND) += snd-soc-pisound.o
 obj-$(CONFIG_SND_BCM2708_SOC_FE_PI_AUDIO) += snd-soc-fe-pi-audio.o
+
+snd-soc-ohmbre-codec-objs := ohmbre-codec.o
+obj-$(CONFIG_SND_BCM2835_SOC_I2S) += snd-soc-ohmbre-codec.o
