--- upstream-kernel/sound/soc/bcm/Makefile	2018-10-24 15:28:05.660473203 -0400
+++ overlay/sound/soc/bcm/Makefile	2018-10-24 19:14:19.081070234 -0400
@@ -50,3 +50,6 @@
 obj-$(CONFIG_SND_BCM2708_SOC_FE_PI_AUDIO) += snd-soc-fe-pi-audio.o
 obj-$(CONFIG_SND_RPI_SIMPLE_SOUNDCARD) += snd-soc-rpi-simple-soundcard.o
 obj-$(CONFIG_SND_RPI_WM8804_SOUNDCARD) += snd-soc-rpi-wm8804-soundcard.o
+
+snd-soc-ohmbre-codec-objs := ohmbre-codec.o
+obj-$(CONFIG_SND_BCM2835_SOC_I2S) += snd-soc-ohmbre-codec.o
