#!/bin/bash

# "./install" copies boot and kernel code to remote ohmbre or its sd card if mounted locally
# "./install debug" disables bluetooth and reuses the uart as a linux console using out gate jacks 3/4 as RX/TX


release=4.15.0-ohm+
host=o
mntpt="./mnt"
set -e

if [ -b /dev/disk/by-label/OHMBOOT ] && [ -b /dev/disk/by-label/ohmsystem ]; then
    echo "installing to sd card"
    mkdir -p $mntpt
    mkdir -p $mntpt/b
    mkdir -p $mntpt/s
    [[ $(findmnt -S LABEL=OHMBOOT -M $mntpt/b) ]] || mount /dev/disk/by-label/OHMBOOT $mntpt/b
    [[ $(findmnt -S LABEL=ohmsystem -M $mntpt/s) ]] || mount /dev/disk/by-label/ohmsystem $mntpt/s
    cp dist/boot/* $mntpt/b/
    rm -rf $mntpt/s/lib/modules/*
    cp -a dist/lib/modules/$release $mntpt/s/lib/modules/

    if [ "$1" = "debug" ]; then
	sed -i -e 's/ohmbre.dtb/debug.dtb/g' $mntpt/b/config.txt
    fi
    
    sync   
    umount -A $mntpt/b
    umount -A $mntpt/s
    rmdir $mntpt/b $mntpt/s $mntpt
else
    echo "installing to live host at $host"
    scp dist/boot/* $host:/boot/
    if [ "$1" = "debug" ]; then
	cat dist/boot/config.txt | sed -e 's/ohmbre.dtb/debug.dtb/g' | ssh $host 'cat > /boot/config.txt'
    fi
    pushd dist/lib/modules
    ssh $host rm -rf /lib/modules/$release
    tar cf - $release | ssh $host '(cd /lib/modules/; tar xf - )'
    popd
    ssh $host depmod
    ssh $host sync
fi
