--- upstream-kernel/arch/arm/boot/dts/Makefile	2018-10-24 15:28:01.747139697 -0400
+++ overlay/arch/arm/boot/dts/Makefile	2018-10-24 19:06:45.494383618 -0400
@@ -8,7 +8,8 @@
 	bcm2709-rpi-2-b.dtb \
 	bcm2710-rpi-3-b.dtb \
 	bcm2710-rpi-3-b-plus.dtb \
-	bcm2710-rpi-cm3.dtb
+	bcm2710-rpi-cm3.dtb \
+	ohmbre.dtb
 
 dtb-$(CONFIG_ARCH_ALPINE) += \
 	alpine-db.dtb
