--- upstream-kernel/arch/arm64/boot/dts/broadcom/Makefile	2018-10-24 15:28:01.937139705 -0400
+++ overlay/arch/arm64/boot/dts/broadcom/Makefile	2018-10-24 19:03:11.191040852 -0400
@@ -4,6 +4,8 @@
 dtb-$(CONFIG_ARCH_BCM2709) += bcm2710-rpi-3-b.dtb
 dtb-$(CONFIG_ARCH_BCM2835) += bcm2710-rpi-3-b.dtb
 dtb-$(CONFIG_ARCH_BCM2835) += bcm2710-rpi-3-b-plus.dtb
+dtb-$(CONFIG_ARCH_BCM2835) += ohmbre.dtb
+dtb-$(CONFIG_ARCH_BCM2835) += debug.dtb
 
 subdir-y	+= northstar2
 subdir-y	+= stingray
